Add textarea component
SIMPLENIGHTDV/simplenight-ui pull request #11
Opened 2023-01-02 15:29 UTC by isabel-light-it

2023-01-02 20:53 UTC, daiana-simplenight commented on src/components/Inputs/TextArea/TextArea.tsx
> +  size = 'large',
The textarea input uses numbers of rows instead of size.

2023-01-02 20:53 UTC, daiana-simplenight requested changes
Needs to rebase with the base branch and the test of the component.

2023-01-03 14:57 UTC, NakaSimpleNight requested changes

2023-01-03 14:57 UTC, NakaSimpleNight commented on src/components/Inputs/TextArea/TextArea.stories.tsx
> +};
Would be great to add more examples, with idle, error, and success, just to have them

2023-01-03 17:39 UTC, NakaSimpleNight approved these changes

2023-01-03 17:39 UTC, merged