Feature/saf 3483/search input
SIMPLENIGHTDV/simplenight-ui pull request #13
Opened 2023-01-02 20:49 UTC by daiana-simplenight

Add search input component

https://simplenight.atlassian.net/browse/SAF-3483

2023-01-03 15:18 UTC, NakaSimpleNight requested changes

2023-01-03 15:18 UTC, NakaSimpleNight commented on src/components/Inputs/PasswordInput/PasswordInput.test.tsx
> +  });
Can value be empty?

2023-01-03 15:18 UTC, NakaSimpleNight commented on src/icons/regular/stories/Sarch.stories.tsx
> +import React from 'react';
Wrong file name, typo

2023-01-03 15:18 UTC, NakaSimpleNight commented on src/components/Inputs/SearchInput/SearchInput.tsx
> +    idle: `${idleColor}`,
Is this ok? Idle is a border color instead of a text-color? Why do we have different text-green and then border-dark

2023-01-03 16:23 UTC, daiana-simplenight commented on src/components/Inputs/PasswordInput/PasswordInput.test.tsx
> +  });
It can be `''`

2023-01-05 13:58 UTC, NakaSimpleNight approved these changes

2023-01-05 13:58 UTC, merged