Creates recomendation card component
SIMPLENIGHTDV/simplenight-ui pull request #59
Opened 2023-03-27 16:32 UTC by Alejandro-Simplenight

# TITLE - [View JIRA Ticket](https://simplenight.atlassian.net/browse/WLL-45)

## Adds Recommendation Card component, it is able to recibe 3 props described on storybook view

when "src" is undefined it shows our emptyImage component
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/117793755/228004697-a7bb88ba-7c36-47f1-941e-cd4ecd0191b7.png">

other wise it shows the image as expected

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/117793755/228005293-3ef7d38c-4ff5-41f5-b4a7-4eb005aaa6da.png">

2023-03-27 17:46 UTC, rodriguez-gaston-simplenight submitted a review, later dismissed

2023-03-28 16:56 UTC, NakaSimpleNight approved these changes

2023-03-28 16:56 UTC, NakaSimpleNight commented on src/components/RecomendationCard/RecomendationCard.tsx
> +};
Let's avoid ternaries, use guard clauses

2023-03-28 17:00 UTC, NakaSimpleNight requested changes

2023-03-28 17:00 UTC, NakaSimpleNight commented on src/components/RecomendationCard/RecomendationCard.tsx
> +};
The selected state missing, let's see where the guys apply it and check if we need it 
![image](https://user-images.githubusercontent.com/105232333/228313988-a4334681-bbaa-4cee-a994-f3ac7246e00c.png)

2023-03-29 15:01 UTC, Alejandro-Simplenight commented on src/components/RecomendationCard/RecomendationCard.tsx
> +};
After checking the figma mockup, outline behavior, and some example places where we use this component I noticed that it should be a button, so I modified it.

2023-03-30 16:04 UTC, NakaSimpleNight approved these changes

2023-03-30 16:04 UTC, merged